AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  orders-api

Globals:
  Function:
    Runtime: python3.8
    Architectures:
      - x86_64
    Timeout: 30
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable

Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: order/
      Handler: create_order.lambda_handler
      Events:
        CreateOrder:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
  ReadOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: order/
      Handler: read_order.lambda_handler
      Events:
        CreateOrder:
          Type: Api
          Properties:
            Path: /orders/{id}
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable

Outputs:
  CreateOrdersAPI:
    Description: "API Gateway endpoint for creating orders"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/orders"
  CreateOrderFunction:
    Description: "Create order function ARN"
    Value: !GetAtt CreateOrderFunction.Arn
  CreateOrderFunctionIamRole:
    Description: "Create order function IAM Role ARN"
    Value: !GetAtt CreateOrderFunctionRole.Arn
