version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "grade-calculator-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xtv72j7bfj6"
s3_prefix = "grade-calculator-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
