name: serverless-app

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: aws-serverless-foundations

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Dependencies and test
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'
      run: 'npm install'

    - name: Run Tests
      run: |
        npm run test
  
  build-layers:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Build serverless layer
    container:
      image: "node:14-buster"
    steps:
      - uses: actions/checkout@v2

      - run: |
        npm install --production
        mkdir nodejs
        mv node_modules nodejs
        apt update -y && apt install zip -y
        zip -r nodejs.zip nodejs/

      - uses: actions/upload-artifact@v2
        with:
          name: nodejs-deps
          path: nodejs.zip
  
  deploy:
    name: Deploy serverless stack
    runs-on: ubuntu-latest
    needs: [tests, build-layers]
    steps:
    - uses: actions/checkout@v2.0.0

    - name: NPM - Load cached venv
      id: cached-npm-dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: npm-${{ runner.os }}-${{ hashFiles('**/package.json') }}

    - name: NPM - Install dependencies
      if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'
      run: 'npm install'

    - uses: actions/download-artifact@v2
      with:
        name: nodejs-deps
        path: app/

    - name: Deploy using serverless
      run: 'npx serverless deploy'
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: |
          Your serverless app was deployed!
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
